# Setup
title:               Zjhong Blog
tagline:             'where amazing happens'
description:         ''
paginate:            5
baseurl:             ''
# About/contact
author:
  name:              Junhong Zhang
  email:             zjhong_sysu@outlook.com

markdown: kramdown

rdiscount:
  extensions:
    - autolink      # greedily urlify links
    - footnotes     # footnotes
    - smart         # typographic substitutions with SmartyPants

gems: [kramdown, jekyll-paginate]